# Generated by Django 5.2.5 on 2025-08-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
