# Generated by Django 5.2.5 on 2025-08-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0003_rename_creat_at_category_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
