# Generated by Django 5.2.5 on 2025-08-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
